services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "80:80"
      - "8001:8001"
      - "8002:8002"
